---
- name: Start setup
  hosts: local
  become: yes
  become_user: "{{ user }}"
  gather_facts: no

  roles:
    - { role: lib/upgrade,    tags: upgrade }
    - { role: lib/keybase,    tags: keybase }
    - { role: lib/git-config, tags: git }
    - { role: lib/pacman,     tags: pacman }
    - { role: lib/aur,        tags: aur }
    - { role: lib/config,     tags: config }

