---
- name: Start setup
  hosts: localhost
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Pacman upgrade
      pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - upgrade
    - name: AUR upgrade
      aur: upgrade=yes
      tags:
        - upgrade
    - name: Git configure
      become_user: msilveira
      command: "{{ item }}"
      with_items:
        - git config --global user.email "msilveira.ti@gmail.com"
        - git config --global user.name "Moises Silveira"
      tags:
        - git

  roles:
    - role: lib/keybase
      tags:
        - keybase
    - role: lib/pacman
      tags:
        - pacman
    - role: lib/aur
      tags:
        - aur
    - role: lib/config
      tags:
        - config

