---
user: msilveira
pacman_packages:
  - xclip
  - the_silver_searcher
  - python-pip
  - ruby
  - docker
  - go
  - gnu-netcat
  - bind-tools
  - net-tools
  - thunar-archive-plugin
  - thunar-volman
